### ISSUE TITLE
load_sound_file has some problems

### ISSUE THREAD

**Issue by Geson-anko** [Geson-anko/PynkTromboneGym#149]
pynktrombonegym/spectrogram.pyの中の`load_sound_file`に次の問題点があります。  

- `max_value`の計算方法は `2**(8*sample_width - 1)`が正しい。
- int型で書き込まれた音声ファイルのみを想定しており、float型で書き込まれたファイルの読み込みが正常に動作しない恐れがある。  
    `sound.sample_width`が返す値は波形の1サンプルあたりのバイト数であるため、値域が[-1,1]かつfloat32型だった場合に、全ての要素が `1 / (2 ** 31)`倍され値が消失する恐れがある。 

### Source code of spectrogram.py

```py
def load_sound_file(file_path: Any, sample_rate: int) -> np.ndarray:
    """Load sound wave from file.
    Fix sound channel to 1, sample_rate, and
    normalize range to [-1,1].
    Args:
        file_path (str): Path to the sound file.
    Returns:
        waveform (ndarray): Range[-1,1]
            Waveform of loaded sound.
    """

    sound: AudioSegment = AudioSegment.from_file(file_path)

    if sound.frame_rate != sample_rate:
        sound = sound.set_frame_rate(sample_rate)
    if sound.channels != 1:
        sound = sound.set_channels(1)

    max_value = 2 ** (8 * sound.sample_width)
    wave = np.array(sound.get_array_of_samples()).reshape(-1) / max_value
    wave = wave.astype(np.float32)
    return wave
```

**Comment by cehl-kurage** [comment]
>値域が[-1,1]かつfloat32型だった場合に、全ての要素が 1 / (2 ** 31)倍され値が消失する恐れがある。  

について
- 32bit floatかつすでに[-1, 1]になっている場合だけが問題ですか？  

すでに恣意的に[-1, 1]にされているものをもう一度スケーリングしようとするのはまずいため、[-1, 1]になっている場合はそのまま使いたいという感じなのかなという理解を今のところしています。

**Comment by Geson-anko** [comment]
@cehl-kurage その通りです。

**Comment by sandeepnmenon** [comment]
Issue resolved in #151
