### ISSUE TITLE
Rename env.py to environment.py

### ISSUE THREAD

**Issue by Geson-anko** [Geson-anko/PynkTromboneGym#74]
`env`は様々なモジュール、関数名として使用されることが多いため、`environment.py`にリネームする必要があります。

**Comment by sandeepnmenon** [comment]
You are right. "env" is often used as a name for various modules and functions, so to avoid confusion or potential conflicts, it would be better to use a more descriptive name, hence environment.py.

I can raise a PR for this

**Comment by Geson-anko** [comment]
@sandeepnmenon Merged to `master` and updated version to `0.2.0`! #154
